# handlers/main.yml
---
- name: Apply nmstate configuration
  listen: nmstate_config_changed
  become: true
  service:
    name: nmstate
    state: restarted

- name: Apply lldpd configuration
  listen: lldpd_config_changed
  become: true
  service:
    name: lldpd
    state: restarted